Overview api calls setup
rpp32-fec-hedgehog/fec-atelier pull request #13
Opened 2021-12-17 21:18 UTC by dwightdoran

Apologies for this but there is a lot of changes here....

-I added all of the routes from the client --> server --> API
-Refactored my API functions (added callback as parameter)
-Added all of the routes I am going to need to the server besides the cart post route i'll need (not sure of how i want to implement that yet)
-The purpose of this branch was just to set up the routes from the client to the API and back // make sure each component is getting the data it needs and nothing more.

Again apologies for the large PR (got in the zone and didn't realize how much I was writing)

Also I had to cancel my last PR because I left my key in there. I'm creating a new one now but I'd like to get that figured out soon.

2021-12-17 22:09 UTC, RobStafford approved these changes
Hi Dwight--I see two potential issues, but neither I'd request a change on: 1) if we all store our api token in the same variable (Dominic and I had picked GITHUB_API_TOKEN, but idc) then the one import statement will work for all four of us, without a need for individual token imports, and 2) you've hard coded an item id in to the props you're passing down from src/index.jsx to Overview, I'd suggest you put it as the default in state, instead, as the component will still function correctly when state changes, and you'll get the behavior you want for testing--that's what I did in my incoming repo).

2021-12-18 00:02 UTC, DominicMonares requested changes
Hey Dwight, looks great overall! Only changes I see are the newlines at the end of some docs again (please let me know if this is too nitpicky, I know it doesn't affect the code but github picks up on it) and the hardcoded item id.

I did the same thing for my id but I think Rob's suggestion to put it as a default state is a good one. No need to change the state in index.jsx, I'm putting the default on my QA-framework PR, just the reference to the state.

We should all discuss the API key setup when we meet tomorrow, but for now I'm good with it as is.

2021-12-18 00:02 UTC, DominicMonares commented on utils/apiCalls.js
> +// }
newline needed

2021-12-18 00:02 UTC, DominicMonares commented on client/src/index.jsx
> +          <Overview itemid={59553} />
I think Rob's suggestion to put a hardcoded id in the App state is a good one, that way we can keep everything dynamic. I'm going to make that same change to my QA-framework

2021-12-18 00:02 UTC, DominicMonares commented on client/src/components/Overview/components/StyleSelector.jsx
> +export default StyleSelector;
newline needed

2021-12-18 00:02 UTC, DominicMonares commented on client/src/components/Overview/components/ProductInfo.jsx
> +export default ProductInfo;
newline needed

2021-12-18 00:02 UTC, DominicMonares commented on client/src/components/Overview/components/AddToCart.jsx
> +export default AddToCart;
newline needed

2021-12-18 00:02 UTC, DominicMonares commented on client/src/components/Overview/Overview.jsx
> +export default Overview;
newline needed

2021-12-18 15:46 UTC, dwightdoran commented
Thank you for the suggestions gentlemen. I have made the changes and am awaiting your approval good sirs.

2021-12-18 19:20 UTC, merged