Overview component creation
rpp32-fec-hedgehog/fec-atelier pull request #8
Opened 2021-12-16 16:07 UTC by dwightdoran

I've created the skeleton for the Overview widget. In doing so, I added some files and folders. Please look at everything and give honest feedback of file structure, naming conventions, etc. I'm happy to change anything that is an issue.

2021-12-16 23:43 UTC, DominicMonares requested changes
The logic looks solid! Only changes I notice are very minor syntax additions/changes, I made comments in each area. Looking good other than that.

Regarding the file structure, I can't remember if we decided on anything regarding child components for our widgets - whether we're putting them all in the same components folder or sub folders for each widget within that components folder. We should confirm with the rest of the group, but I like the way you have it structured and would vote to go in that direction.

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/Overview.jsx
> +    super(props)
semi-colon missing after super and state

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/Overview.jsx
> +
unnecessary empty line

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/AddToCart.jsx
> +export default AddToCart;
newline required at end of doc

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/ImageGallery.jsx
> +export default ImageGallery;
newline required at end of doc

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/ProductInfo.jsx
> +export default ProductInfo;
newline required at end of doc

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/StyleSelector.jsx
> +export default StyleSelector;
newline required at end of doc

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/AddToCart.jsx
> +    super(props)
semi-colon missing after super and state

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/ImageGallery.jsx
> +    super(props)
semi-colon missing after super and state

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/ProductInfo.jsx
> +    super(props)
semi-colon missing after super and state

2021-12-16 23:43 UTC, DominicMonares commented on client/src/components/Overview/components/StyleSelector.jsx
> +    super(props)
semi-colon missing after super and state

2021-12-17 15:26 UTC, dwightdoran commented
Changes made if someone could merge this.

2021-12-17 15:37 UTC, merged